
spring:
  application:
    name: proxy
  cloud:
    zookeeper:
      connect-string: localhost:2181

zuul:
  routes:
    books:
       serviceId: book
#      url: http://localhost:9001
    accounts:
       serviceId: account
#      url: http://localhost:9002

server:
  port: 9000

