spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Pyshankov/spring-cloud-config
#          uri: file://${user.home}/Desktop/spring-cloud-config/
          search-paths: ConfigData
  application:
    name: config-server
server:
  port: 8888